### ISSUE TITLE
a bug I can not solve

### ISSUE THREAD

**Issue by Yuanzhisheng** [hjptriplebee/Chinese_poem_generator#4]
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    poems = MCPangHu.test()
  File "/Users/wangxiaoli/Chinese_poem_generator/model.py", line 105, in test
    saver.restore(sess, checkPoint.model_checkpoint_path)
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [92] rhs shape= [9989]
	 [[Node: save/Assign_3 = Assign[T=DT_FLOAT, _class=["loc:@softmax/b"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](softmax/b, save/RestoreV2:3)]]

Caused by op u'save/Assign_3', defined at:
  File "main.py", line 28, in <module>
    poems = MCPangHu.test()
  File "/Users/wangxiaoli/Chinese_poem_generator/model.py", line 101, in test
    saver = tf.train.Saver()
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 835, in _build_internal
    restore_sequentially, reshape)
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 494, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 185, in restore
    self.op.get_shape().is_fully_defined())
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 283, in assign
    validate_shape=validate_shape)
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/Users/wangxiaoli/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [92] rhs shape= [9989]
	 [[Node: save/Assign_3 = Assign[T=DT_FLOAT, _class=["loc:@softmax/b"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](softmax/b, save/RestoreV2:3)]]

I just try to run the program and I find there exists some problems... I can not solve it. Would you please help me?

**Comment by Yuanzhisheng** [comment]
python2

**Comment by Yuanzhisheng** [comment]
Thanks very much and look forward to your reply.

**Comment by hjptriplebee** [comment]
@Yuanzhisheng 你tensorflow版本多少？改过config里的参数没？训练还是测试的时候遇到这个问题？有没有把模型文件删除后重新训练看看呢？

**Comment by Yuanzhisheng** [comment]
tensorflow 版本是1.8.0
没有改过参数
测试的时候遇到的问题。。

**Comment by hjptriplebee** [comment]
@Yuanzhisheng 你把模型文件删掉，重新训练看看，这个错误我认为应该有两种可能：
1.你改了某些参数，导致网络结构变掉了，原来的参数不适用了；
2.TensorFlow新版本改变了原来的存储方式，毕竟我原来不是在1.8上开发的，我有时间会尝试用1.8测试一下，有问题会修复。

**Comment by hjptriplebee** [comment]
@Yuanzhisheng 我试过了，改掉参数再用原来的模型文件测试会出现和你一样的情况，所以应该是你无意中改了什么参数。删掉模型文件，重新训练自己的模型就行了，如果想使用我训练的模型，务必保证参数未修改，可以重新clone一份代码。

**Comment by Yuanzhisheng** [comment]
好的我先尝试一下，谢谢

**Comment by Yuanzhisheng** [comment]
你好，我重新下载了这个代码，直接在终端上运行main，但是也出现了这个问题。。我不清楚是为什么。。。

**Comment by hjptriplebee** [comment]
@Yuanzhisheng 我在travis上用python2.7的环境跑了一下，出现相同的问题输出。我觉得原因是我在python3的TensorFlow下训练的模型无法迁移到python2。还是建议你自己训练模型，调用我train的模块就行了，要不就在相同的环境下用我的模型。

**Comment by Yuanzhisheng** [comment]
很感谢，谢谢
