### ISSUE TITLE
jupyter

### ISSUE THREAD

**Issue by Mengguangkai** [hjptriplebee/Chinese_poem_generator#5]
我下载下来程序，在jupyter上直接运行main.py，出现

usage: ipykernel_launcher.py [-h] [-m {train,test,head}]
ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\Administrator\AppData\Roaming\jupyter\runtime\kernel-9f24a74d-ad9e-402b-9a5f-40741cbea4f4.json
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

D:\anaconda install\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py:2971: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

这么一个错误，不知道怎么解决。
希望能回答一下啊。
没有模型，想自己训练，但是又不知道哪个是。
求助。

**Comment by hjptriplebee** [comment]
@Mengguangkai 你直接运行的话，默认是使用训练好的模型，就是我train的poetrySong。
你想训练的话要加运行参数-m train，至于jupyter怎么加载运行参数我不太清楚...
我一般都是pycharm + 运行参数， 或者直接在终端里运行。

**Comment by Mengguangkai** [comment]
但是你不是说，git库中没有放训练好的模型吗？

我直接在cmd里运行main的话（我输入代码python main.py  -m test ），提示gbk问题，但是我是python3.5，tensorflow1.8，有点蒙 = =

**Comment by hjptriplebee** [comment]
@Mengguangkai  [https://www.zhihu.com/question/36368902](https://www.zhihu.com/question/36368902) FYI.
我的意思是没放所有模型，你看checkpoint里不是有poetrySong的模型吗。只不过是没有宋词、诗经等等其他任务的模型

**Comment by Mengguangkai** [comment]
我使用的是python3.5版本，在运行main时，会报错data.py打开文件时“file = open(filename, 'r')”，出现这个错误“UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 2: illegal multibyte sequence”，然后我改正的方法：
（一）如果我改成‘rb’，下面又会报错TypeError: a bytes-like object is required, not 'str'
（二）我改成file = open(filename, 'r',errors='ignore')，这时候会出现：runfile('C:/Users/Administrator/main.py', wdir='C:/Users/Administrator')
Reloaded modules: data, config, model
训练样本总数： 249654
测试样本总数： 0
genrating...
Traceback (most recent call last):

  File "<ipython-input-37-1a8b7e878157>", line 1, in <module>
    runfile('C:/Users/Administrator/main.py', wdir='C:/Users/Administrator')

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Administrator/main.py", line 28, in <module>
    poems = MCPangHu.test()

  File "C:\Users\Administrator\model.py", line 98, in test
    logits, probs, stackCell, initState, finalState = self.buildModel(self.trainData.wordNum, gtX)

  File "C:\Users\Administrator\model.py", line 19, in buildModel
    embedding = tf.get_variable("embedding", [wordNum, hidden_units], dtype = tf.float32)

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1317, in get_variable
    constraint=constraint)

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1079, in get_variable
    constraint=constraint)

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 425, in get_variable
    constraint=constraint)

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 733, in _get_single_variable
    name, "".join(traceback.format_list(tb))))

ValueError: Variable embedding/embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)



不知道怎么改了。

**Comment by Mengguangkai** [comment]
麻烦老铁帮忙看一下上面那个问题。还有一个问题，（二）中测试样本是什么，我这个为0，正常吗？

**Comment by hjptriplebee** [comment]
@Mengguangkai （一）的改法肯定不对，因为这个数据不是二进制文件，（二）的改法既然可以看到训练样本数，就说明从文本读入数据没有问题了，测试样本只有在evaluate的时候才不为0，你这个0是正常的。从
```
ValueError: Variable embedding/embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:
```
这里看，jupyter之前的进程可能没关掉，导致变量重复定义了。
但是我也不敢确定，因为你的错误最后并没有贴完整，下面应该还有error类型的

**Comment by Mengguangkai** [comment]
695147837，方便加一下qq问一下吗。

上面那个是贴全了的，听你这么一说，然后
我又运行了一遍，直接在spyder中运行，出现了下面这个问题：
runfile('C:/Users/Administrator/main.py', wdir='C:/Users/Administrator')
训练样本总数： 249654
测试样本总数： 0
genrating...
INFO:tensorflow:Restoring parameters from ./checkpoints/poetrySong\poem-157999
Traceback (most recent call last):

  File "<ipython-input-1-1a8b7e878157>", line 1, in <module>
    runfile('C:/Users/Administrator/main.py', wdir='C:/Users/Administrator')

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Administrator/main.py", line 28, in <module>
    poems = MCPangHu.test()

  File "C:\Users\Administrator\model.py", line 105, in test
    saver.restore(sess, checkPoint.model_checkpoint_path)

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [4473] rhs shape= [9989]
	 [[Node: save/Assign_3 = Assign[T=DT_FLOAT, _class=["loc:@softmax/b"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](softmax/b, save/RestoreV2:3)]]

Caused by op 'save/Assign_3', defined at:
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 269, in <module>
    main()
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 265, in main
    kernel.start()
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "D:\anaconda install\envs\tensorflow\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "D:\anaconda install\envs\tensorflow\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "D:\anaconda install\envs\tensorflow\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2909, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-1a8b7e878157>", line 1, in <module>
    runfile('C:/Users/Administrator/main.py', wdir='C:/Users/Administrator')
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/Administrator/main.py", line 28, in <module>
    poems = MCPangHu.test()
  File "C:\Users\Administrator\model.py", line 101, in test
    saver = tf.train.Saver()
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1338, in __init__
    self.build()
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 835, in _build_internal
    restore_sequentially, reshape)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 494, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 185, in restore
    self.op.get_shape().is_fully_defined())
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\ops\state_ops.py", line 283, in assign
    validate_shape=validate_shape)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 63, in assign
    use_locking=use_locking, name=name)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [4473] rhs shape= [9989]
	 [[Node: save/Assign_3 = Assign[T=DT_FLOAT, _class=["loc:@softmax/b"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](softmax/b, save/RestoreV2:3)]]

**Comment by Mengguangkai** [comment]
啊。好像还是第一次（二）那个问题：
ValueError: Variable embedding/embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "D:\anaconda install\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
只有这些了，前面都是一样的。

**Comment by hjptriplebee** [comment]
有value error的那个错误应该是你在一个开着的jupyter里多次run了我的代码，而中间没有手动关闭，Ipython的变量生成以后，在没结束之前是不会自己回收的，所以当你第二次运行的时候出现了reuse的问题。
你贴的InvalidArgumentError这个错误，之前也有人遇到，
[https://github.com/hjptriplebee/Chinese_poem_generator/issues/4](https://github.com/hjptriplebee/Chinese_poem_generator/issues/4)
最后证明是他的运行环境和我不一致，如果你想用我的模型，要保证linux(centos, ubuntu) + python3 + tensorflow1.2以上的环境，不然需要删掉模型重新训练模型。

**Comment by Mengguangkai** [comment]
那我直接删掉checkpoint里的poetrySong的中的东西，然后 python main.py -train 等训练好了生成模型，然后再运行-m test 就好了是吧？【哭】【哭】

**Comment by hjptriplebee** [comment]
应该吧，别再出幺蛾子了，搞深度学习还是用linux吧，还有你用cpu训练就算你运行成功了，也不知道要train几天......

**Comment by Mengguangkai** [comment]
谢谢老铁啦！我向系里申请服务器帐号了，下周应该可以用到，但好像挺麻烦【哭】
ubuntu都有，但是运行起来觉得linux有点卡，就没有用。
因为cpu慢，我下了gpu版本的tensorflow。。
看来还是linux好用啊。

**Comment by Mengguangkai** [comment]
总之谢谢胖虎！谢谢老铁啦。
