### ISSUE TITLE
请问一下执行main.py出现错误

### ISSUE THREAD

**Issue by infiniteHY** [hjptriplebee/Chinese_poem_generator#8]
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    trainData = data.POEMS(trainPoems)
  File "D:\study\1.毕业设计\Chinese_poem_generator-master\data.py", line 17, in __init__
    for line in file:  #every line is a poem
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 2: illegal multibyte sequence
我刚开始学照着网上帖子安装了环境Windows，python3.6，TensorFlow1.8-gpu，别的也不太会，不知道该看什么开始学起，想先运行出来你的。看你别的issues里删除poetrySong里的内容，但我又出错了
python main.py -train
usage: main.py [-h] [-m {train,test,head}]
main.py: error: unrecognized arguments: -train
我感觉我也不懂怎么运行，又不知道该怎么办，请求帮助，谢谢啦。

**Comment by infiniteHY** [comment]
编码问题，自己解决了
